
export const RESERVE_DATA = [
  {
    ID_RESERVA: 1,
    FECHA_RESERVA: '2023/10/26',
    reserve_time: "18:00",
    light: 'Sí',
    installation: 'Tenis',
    court: "Pista 1",
    price: 7,
    paid: true,
  },
  {
    id: 2,
    reserve_date: '2023/10/23',
    reserve_time: "19:00",
    name: 'Alex',
    surname: 'González Roquero',
    light: 'No',
    installation: 'Tenis',
    court: "Pista 3",
    price: 6,
    paid: true,
  },
  {
    id: 3,
    reserve_date: '2023/10/20',
    reserve_time: "09:00",
    name: 'María',
    surname: 'Martínez Uriarte',
    light: 'Sí',
    installation: 'Frontón',
    court: "1",
    price: 7,
    paid: false,
  },
  {
    id: 4,
    reserve_date: '2023/10/16',
    reserve_time: "18:00",
    name: 'Ayat',
    surname: 'Fernández Isasi',
    light: 'Sí',
    installation: 'Pádel',
    court: "1",
    price: 7,
    paid: false,
  },
  {
    id: 5,
    reserve_date: '2023/10/09',
    reserve_time: "19:00",
    name: 'Ayat',
    surname: 'Fernández Isasi',
    light: 'No',
    installation: 'Tenis',
    court: "Pista 3",
    price: 6,
    paid: false,
  },
  {
    id: 6,
    reserve_date: '2023/09/20',
    reserve_time: "17:00",
    name: 'Soraya',
    surname: 'Letto',
    light: 'Sí',
    installation: 'Pádel',
    court: '1',
    price: 7,
    paid: false,
  },
];